### ISSUE TITLE
JOSS Submission Review (Reviewer 1): Documentation

### ISSUE THREAD

**Issue by lelaus** [tmfrln/paraqus#2]
This issue is related to the [JOSS submission review](https://github.com/openjournals/joss-reviews/issues/5729).

Please, you can find below some remarks, questions, and suggestions about the documentation provided with the package. After a first part where general points are described, the next points are subdivided according to the sections of the documentation.

Please, do not hesitate to contact me in case of any related doubt.

General Remarks
===========

- [ ] top left corner, under the *Paraqus* name: I'd suggest to write the version of *Paraqus* this doc is referring to instead of *latest*;

- [x] make the first letter of the first word after the first colon lowercase;

- [x] *paraqus* term: I'd suggest to write *Paraqus* with the first uppercase letter and either in italics or bold through the entire documentation;

- [x] *python* term: I'd suggest to use always the first uppercase letter everywhere in the documentation;

- [x] I'd suggest using *you* as the subject instead of *we* through the entire documentation;

- [x] I'd suggest to homogenize the itemized lists: sometimes the punctuation is missing at the end of single items;

- [x] I'd suggest to homogenize the itemized lists: please choose whether writing the first letter of each item uppercase or lowercase, and apply this choice everywhere through the documentation.

Structure of the Documentation
==============================

- [x] Before the *Installation* section I'd suggest to add:
  - [x] a section *Introduction* where clearly describing the statement of need of *Paraqus* project, that is: what problems it is designed to solve, who the target audience is, and its relation to other works;
  - [x] a section *Project Structure* where briefly describing the structure of the project, thus giving the user an overview of the entire repo;
  - [x] a *Dependencies* section where saying what already stated in the subsection *Dependencies* of the section *Installation*;

- [x] I'd suggest to add information on how to compile the documentation, maybe within the section *Installation*;

- [ ] I'd suggest to move the section *Tests* before the *API* section, since they are both intended to support the developers;

- [x] I'd suggest to add a section *Contacts* where defining:
  - how the reader can contact the authors;
  - how to reader can contribute to the project (for instance, just by linking the file in the main folder of the project);
  - how the reader can cite the project in any work in which she/he will use it;

- [x] I'd suggest to add a section *License* where specifying the license for use of the project; this could be just a link to the license file that is present in the main folder of the project;

- [ ] at the end of the documentation, I'd suggest to add a section *References* where specifying all the involved literature references;

- [ ] I'd suggest to enrich the **README** file with some of the information that are provided in the documentation. To avoid repetitions, I'd suggest to write it only once for the **README** file, and then to re-use it in the corresponding sections of the doc. In addition to the sections already present in the **README**, I'd suggest to apply the following modifications/additions:
  - [ ] Statement of need (the actual is too short and not complete);
  - [ ] Project Structure;
  - [ ] Dependencies;
  - [ ] Installation;
  - [ ] Contacts;
  - [ ] References.

Installation
============

- [x] in place of "inside of" I'd suggest "inside".

Installation > Using Paraqus only outside of Abaqus
---------------------------------------------------

- [x] instead of *outside of* I'd suggest *outside*;

- [x] to avoid the repetition of *installed* term, I'd suggest: *Assuming Python is already available on your machine, ...*;

- [x] instead of *Python package index* I'd suggest *Python Package Index*;

- [x] instead of *python installation* I'd suggest *Python version*;

- [x] *pip* ==> since it is a command, I'd suggest to better distinguish it from the other common words here and across the entire documentation by using code style `pip`.

Installation > Using Paraqus within Abaqus
------------------------------------------

- [x] for symmetry reasons, instead of *within Abaqus* I'd suggest *inside Abaqus*;

- [x] instead of *we need to download or install Paraqus* I'd suggest *first of all, you need to install Paraqus*;

- [x] *they might be dependent on your operating system.*: I would expect this sentence to be followed by specific considerations for each of the main operating systems, i.e. Linux, Windows and MacOS. On the other hand, the two following subsections should be introduced by a dedicated sentence. I'd suggest replacing the original sentence with one that introduces the following two subsections.

Installation > Using Paraqus within Abaqus > If you already have Python installed
---------------------------------------------------------------------------------

- [x] *follow the instructions above*: although the referenced section is some lines above, I'd suggest to add the link to it;

- [x] *for an example output ['/home/user/lib/python3.11/site-packages/paraqus'], we need to note down the path /home/user/lib/python3.11/site-packages.*:
  - [x] I'd suggest to dedicate a specific bullet point to this sentence;
  - [x] I'd suggest *take note of the output by removing the ending* `/paraqus` *term; the resulting string represents the path to the location where the Paraqus package is installed. For instance, should the output be* `['/home/user/lib/python3.11/site-packages/paraqus']`*, you need to note down the path* `/home/user/lib/python3.11/site-packages`;

- [x] `sys.path.append("path")`: I'd suggest to change in `sys.path.append("<path>")` for better differentiation from the *path* string.

Installation > Using Paraqus within Abaqus > If you do not have Python installed
--------------------------------------------------------------------------------

- [x] *download the repository, and unpack it to a path of your choice,*: is there a reason why the cloning of the repo is not suggested? This would make the update of the package simpler;

- [x] *locate the `src` directory inside the directory*: I'd suggest *locate the `src` directory inside the repository folder* to avoid the repetition;

- [x] *In our example,*: I'd suggest *In the above example,*;

- [x] `sys.path.append("path")` ==> see comment in the previous section.

Installation > Adding Paraqus to the python path (advanced, but recommended)
----------------------------------------------------------------------------

- [ ] What about making this addition mandatory? It would simplify the entire installation procedure described above;

- [x] *to all your files*: I'd suggest to be more precise by writing *Python scripts*;

- [x] *Since this step is dependent on the operating system, it is not described here in detail, but you have to google for your system.*: I'd suggest helping the reader find relevant hints on the steps to follow by providing a link for Linux, Windows and MacOS OSs. These links are intendend as examples, but should help the novice reader to accomplish the task more quickly.

Dependencies
------------

- [x] I'd suggest dedicating a separate chapter to this topic before the *Installation* chapter, thus moving this section up one level;

- [x] The information of the minimum Python version under which *Paraqus* can work is missing. If I understood correctly, *Paraqus* should work on both versions 2.7 and 3 of Python. If so, I'd suggest to add such information;

- [x] it seems that the only dependency is *Numpy*; is it possible to provide a minimum version against which *Paraqus* has been tested?

- [x] I'd suggest to mention as optional dependencies all the packages needed for compiling the documentation and for performing the tests, if any;

- [x] I'd suggest to call the *Numpy* module always in the same way, while here both the lowercase and uppercase versions are used. Please make them homogeneous. In addition, to better differentiate the name of a Python module, I'd suggest to write it in bold or italics across the entire documentation.

Usage
=====

- [x] I'd suggest to add an introductory paragraph at the beginning of the section to give the user an overview about what she/he will find in this section.

Usage > Usage with pure Python
------------------------------

- [x] I'd suggest to change the section title into *Usage with Python alone*;

- [x] write "vtk" in different style, just to highlight it;

- [x] when class names are written, is it possible to link them to the corresponding class in the API guide?

- [ ] in the sentence before the first table, I'd suggest to add the reference to the table itself, maybe by adding a caption to it.

Usage > Usage with Abaqus
-------------------------

- [x] *The following steps do not change compared to the usage with pure python.*: which are these steps?

- [ ] *The following examples demonstrate ...*: it could be useful to cite the table below, thus adding a caption to the table itself;

- [ ] *the Abaqus input files must be downloaded*: it seems not specified where the user can find such input files and where she/he can download them from;

- [x] *Only then should you go*: should it be *Only then, you should (shall?) go ...*;

- [x] *At the end of each of the Abaqus tutorials, an exemplary pipeline for Paraview is described to visualize the results.*: instead of at the end of the tutorial, maybe would you like to say *at the end of the tutorial docstring*?

- [x] In the folder `examples` there is an additional file named `run_example_abaqus_extrusion.py`, which seems not cited among the examples in the documentation. If it is so, I'd suggest to cite and describe it in the documentation if you intend to leave it in the `examples` folder: in addition, in its docstring the Fortran file `UMAT_VMPlasti_LargeStrain.f` is mentioned as a requirement for the example to run, but no information is provided about where to find it.

API
===

- [x] In the introductory paragraph it is written that only classes/methods intended to be used by the users are described in this section. A more standard way to choose which classes/methods to describe in the API guide could be based on whether they are public or private. In addition, among the main aims of the API guide there is the support to the developer's work. What about describing in the API all the public classes/methods?

Known limitations
=================

- [x] Although the entire section is brief, I'd suggest to add an introductory sentence to briefly describe what the user will find in this section;

- [x] About *Abaqus functionality that does not work with Paraqus*, would it make sense to open a dedicated issue in the repo to keep track of such limitation?

- [ ] About *Stuff Paraview can not handle to the best of our knowledge*, I'd suggest to write down the last version of Paraview that has been checked against this feature.

Tests
=====

- [x] *ressources*: substitute with *resources* through the entire documentation;

- [x] *Paraqus comes with two small example Abaqus output databases for tests.*: although they are cited in the following, for clarity, I'd suggest to mention here which and where are the 2 corresponding files;

- [x] *One of the databases is supposed to match your current Abaqus installation, while the other database should be from an older release...*: I'd suggest to rephrase this sentence to be less colloquial: what about describing the requirements by an itemized list? and what about extending this style approach to the entire section?

- [x] If referring to the same folder, I'd suggest to unify how to mention the folder `paraqus/paraqus/tests/resources` in the last two paragraphs of the section *Creating test ressources*;

- [ ] In the `resources` folder there are files not mentioned in the documentation; is there a reason why not mentioning them?

**Comment by tmfrln** [comment]
Thank you for the detailed comments on the docs. I will add some explanations only where we did not directly include the suggestions. If anything remains unclear, please do not hesitate to comment on it.

Some of the proposed additional sections were added, but in a different place than proposed (e.g. license and contact information is located under "extras" in the documentation), to keep the number of sections lower.

> top left corner, under the Paraqus name: I'd suggest to write the version of Paraqus this doc is referring to instead of latest;

"latest" refers to the latest commit in the main branch of the repository, which does not always coincide with a release / version number. However, i changed the display of the stable release to show the version number.

> I'd suggest to move the section Tests before the API section, since they are both intended to support the developers;

The API reference is intended for users who want to write their own scripts or programs using the paraqus package, while tests are intended for developers. Therefore we kep the tests section behind the API reference, and next to the new section "development".

> at the end of the documentation, I'd suggest to add a section References where specifying all the involved literature references;

We tried to separate the contents of paper and documentation rather than repeating things - literature is only referenced in the accompanying paper, therefore we did not add a dedicated section. 

> What about making this addition mandatory? It would simplify the entire installation procedure described above;

Our experience is that this step is a significant barrier for some users, and we therefore want to avoid making it mandatory. The complicated installation is an unfortunate result of the way Python is shipped with Abaqus, which we can not control.

> in the sentence before the first table, I'd suggest to add the reference to the table itself, maybe by adding a caption to it.
The following examples demonstrate ...: it could be useful to cite the table below, thus adding a caption to the table itself;

I personally think the reference to the table is clear here - this is probably a matter of taste :-)

> the Abaqus input files must be downloaded: it seems not specified where the user can find such input files and where she/he can download them from;

The required procedure is described in every example file in detail. The download is performed by Abaqus commands, which are explicitly given in the example files.

> About Stuff Paraview can not handle to the best of our knowledge, I'd suggest to write down the last version of Paraview that has been checked against this feature.

The functionality that does not work is limited by the way data is stored/handled in vtk, so it is independent from the version of ParaView. We rephrased the section description to reflect this fact.

> In the resources folder there are files not mentioned in the documentation; is there a reason why not mentioning them?

We clarified that files are only mentioned here if user action is needed to replace them for successful testing.

> I'd suggest to enrich the README file with some of the information that are provided in the documentation. To avoid repetitions, I'd suggest to write it only once for the README file, and then to re-use it in the corresponding sections of the doc. In addition to the sections already present in the README, I'd suggest to apply the following modifications/additions:

In the spirit mentioned above, i.e. avoiding repetitions (and therefore possible mistakes when updating the package documentation), we only added a small amount of additional information in the README. We did however add an explicit reference to the documentation for the remaining topics.

**Comment by lelaus** [comment]
Hi @tmfrln  ,
Thank you for considering my comments and suggestions!

I have read the updated documentation and your answers.

In general, I appreciate the changes you have made, and I understand your point of view in your answers.

Just a clarification on my suggestion to enrich the content of the **README**: I agree with the need to avoid repetition, it is one of the basic rules that should drive every developer. That is why I suggested writing the contents ONLY in the **README**, and then automatically using it also in the documentation. However, I agree with the new sections added to the documentation: I think they are sufficient to provide the most important information, and they are easily accessible via the link in the **README**.

Following the modifications you applied, before closing the issue, just a few minor comments:

Introduction
========

- *but is designed to be extended for other softwares due to the modular structure*: I'd suggest to change into *but its modular structure allows it to be extended to other software*.

- *Paraqus is intented*: to change into *Paraqus is intended*.

Installation
=======

Installation > Compiling the documentation
------------------------------------------

- I'd suggest to remove the list of dependencies needed for compiling the documentation since this information is already provided in the *Dependencies* section.

- *the docs can be build by running*: to change into *the docs can be built by running*.

Tests
===

Tests > Creating test resources
----------------------------------

- *element_test_current odb*: a point is missing.

Development
=========

Development > Python versions
-----------------------------------

- *Abaqus-specific code in paraqus.abaqus does not have to be compatible to Python 3.X however.*: I'd suggest to change into *Abaqus-specific code in paraqus.abaqus does not need to be Python 3.X compatible.*.

Development > Package structure
-------------------------------------

- Each time an example is provided, I'd suggest to end the corresponding introductory sentence with a colon *:*.

- *manner: They are located ...*: *They* to change from uppercase to lowercase.

- *Only after this step completes successfully is a new release actually pushed to PyPI by a second github action.*: I'd suggest to change into *Only after this step completes successfully, a new release is actually pushed to PyPI by a second github action.*.

**Comment by jstollberg** [comment]
Hi @lelaus,

Thanks a lot for considering our comments and changes. We appreciate that you double checked the documentation again and have made the changes you suggested.

**Comment by lelaus** [comment]
Hi @jstollberg and @tmfrln ,

all the comments and tasks I identified in this issue have been taken into consideration, and either the corresponding changes have been implemented appropriately or comprehensive motivations have been provided.

I'm closing this issue.

Thanks!
