### ISSUE TITLE
JOSS Submission Review (Reviewer 1): Tests

### ISSUE THREAD

**Issue by lelaus** [tmfrln/paraqus#3]
This issue is related to the [JOSS submission review](https://github.com/openjournals/joss-reviews/issues/5729).

Please, you can find below some remarks, questions, and suggestions about the implemented tests.

Please, do not hesitate to contact me in case of any related doubt.

- [ ] I'd suggest to move the `tests` folder outside the base code `src` folder to have a clearer project structure;

- [x] It seems that the implemented tests are intended to cover the main functionalities of the package, which are often the combination of multiple basic functionalities. If this is the case, I'd suggest to improve the robustness of the tests by providing a more detailed coverage of the code; since this requires a great amount of work, I'd suggest to open a dedicated issue to be managed in the future;

- [x] it seems that data are always hard-coded into each test class of each test module; I'd suggest to improve the readability and maintainability of the tests code by collecting them into reference variables, for instance in 	dedicated modules or anyway dedicated reference files, thus defining them just once and making each test access them when needed;

- [x] *test_writers.py*:
  - [x] line 9: unused numpy module;

  - [x] it seems that all the tests check the functionalities of the package in terms of ability of creating and writing output files; a kind of test that seems to be missing is about the data that are written in the output file; if this is so, I'd suggest to implement tests that check the content of the output files. And, as above, if this is a too heavy task, I'd suggest to open a dedicated issue.

**Comment by tmfrln** [comment]
>  I'd suggest to move the tests folder outside the base code src folder to have a clearer project structure;

The tests for the subpackage paraqus.abaqus rely on imports which are only available in the Python interpreter shipped with Abaqus, and therefore can only be executed within this interpreter. If the tests are located in a separate folder, the user wanting to run them would have to manually locate them, or they would need to be in a separate package (with the same drawbacks of adding it to the PATH as for Paraqus). We have therefore decided to keep them as part of the package, and to make them executable through the package API - in our view, this is the easiest and most consistent way for users to run all the tests without too much overhead. 

I hope this explanation is clear, otherwise feel free to follow up on the comment.

**Comment by lelaus** [comment]
Hi @tmfrln and @jstollberg  ,
Thank you for considering my comments and suggestions!

In my opinion, the work done to update the automated tests is very good. The tests now seem well structured and readable.

The motivation you gave for the location of the `tests` folder is clear. Unfortunately, not being able to use the Abaqus Interpreter, I was unable to identify such aspect by myself. I thank you for the clear explanation you have provided.

Before closing the issue, just a few minor comments:

- `test_paraqusmodel.py`:
  - comments of tests at lines 202 and 207 coincide; is this right?
  - docstring at line 375: _withing_ to substitute with _within_;

- `test_writers.py`:
  - comment at lines 114, 170 and 226: to remove _can be_ since written twice.

**Comment by jstollberg** [comment]
Hi @lelaus,

again thanks for having a look at the implementation of our tests again and your valuable feedback. I have modified the files according to your last comments.

**Comment by lelaus** [comment]
Hi @jstollberg and @tmfrln ,

all the comments and tasks I identified in this issue have been taken into consideration, and either the corresponding changes have been implemented appropriately or comprehensive motivations have been provided.

I'm closing this issue.

Thanks!
